### ISSUE TITLE
work/phylogenetics/1.align/pcgaa/all_ND5.aa.align.fas: No such file or directory

### ISSUE THREAD

**Issue by solomonchak** [mht85/MitoPhAST#1]
Hi, I got V3 installed as a singularity image in our HPC. I got the following error when I run:

`/opt/singularity_images/ubuntu-16.04_MitoPhAST-3.0.sif /usr/local/MitoPhAST/V3.0/run_pipeline.pl -acc MG674228,KY944589,NC_023823,KX844712,KY865098,NC_045090 -out ./mitophast --build_trees -mito_gcode 5 -cpu 12 
`

### MITOGENOME COMPILATION ###
Command: /usr/local/MitoPhAST/V3.0/bin/get_ncbi.pl -acc MG674228,KY944589,NC_023823,KX844712,KY865098,NC_045090 -out ./mitophast/work/downloads

Downloading entry for accession MG674228
Downloading entry for accession KY944589
Downloading entry for accession NC_023823
Downloading entry for accession KX844712
Downloading entry for accession KY865098
Downloading entry for accession NC_045090

[ 6 ] mitogenome files can be found in ./mitophast/results/1.mitofiles

### SEQUENCE EXTRACT ###
Command: /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl -in ./mitophast/results/1.mitofiles -out ./mitophast/work/extract -cpu 12 -interactive on

Extracting sequences for KX844712.gb
Extracting sequences for KY865098.gb
Extracting sequences for KY944589.gb
Extracting sequences for MG674228.gb
Extracting sequences for NC_023823.gb
Extracting sequences for NC_045090.gb

>>>WARNING: PFAM/PRINT/rRNA searches failed to identify genes for the following samples:
Missing genes for Typhlatya_mitchelli (KX844712.1): rrnL,rrnS
Missing genes for Macrobrachium_rosenbergii (KY865098.1): rrnL,rrnS
Missing genes for Chlorotocus_crassicornis (KY944589.1): rrnL,rrnS
Missing genes for Heterocarpus_ensifer (MG674228.1): rrnL,rrnS
Missing genes for Neocaridina_denticulata (NC_023823.1): rrnL,rrnS
Missing genes for Palaemon_sinensis (NC_045090.1): rrnL,rrnS
>>>END

These gene sequences may or may not be present in the GenBank/EMBL files, you may want to manually check to confirm this.
In the next step, MitoPhAST will attempt to identify missing sequences based on gene names provided in the input files.
Proceed? (Y/N)y

Identifying gene sequences for Typhlatya_mitchelli (KX844712.1) based on gene IDs in GenBank/EMBL files

Identifying gene sequences for Macrobrachium_rosenbergii (KY865098.1) based on gene IDs in GenBank/EMBL files

Identifying gene sequences for Chlorotocus_crassicornis (KY944589.1) based on gene IDs in GenBank/EMBL files

Identifying gene sequences for Heterocarpus_ensifer (MG674228.1) based on gene IDs in GenBank/EMBL files

Identifying gene sequences for Neocaridina_denticulata (NC_023823.1) based on gene IDs in GenBank/EMBL files

Identifying gene sequences for Palaemon_sinensis (NC_045090.1) based on gene IDs in GenBank/EMBL files
Gene ID successfully identified all missing genes for all samples.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
Use of uninitialized value in string eq at /usr/local/MitoPhAST/V3.0/bin/extract_seqs.pl line 616, <STDIN> line 1.
[ 6 ] sequences extracted for gene ATP6
[ 6 ] sequences extracted for gene ATP8
[ 6 ] sequences extracted for gene COX1
[ 6 ] sequences extracted for gene COX2
[ 6 ] sequences extracted for gene COX3
[ 6 ] sequences extracted for gene CYTB
[ 6 ] sequences extracted for gene ND1
[ 6 ] sequences extracted for gene ND2
[ 6 ] sequences extracted for gene ND3
[ 6 ] sequences extracted for gene ND4
[ 6 ] sequences extracted for gene ND4L
[ 6 ] sequences extracted for gene ND5
[ 6 ] sequences extracted for gene ND6
[ 6 ] sequences extracted for gene ATP6
[ 6 ] sequences extracted for gene ATP8
[ 6 ] sequences extracted for gene COX1
[ 6 ] sequences extracted for gene COX2
[ 6 ] sequences extracted for gene COX3
[ 6 ] sequences extracted for gene CYTB
[ 6 ] sequences extracted for gene ND1
[ 6 ] sequences extracted for gene ND2
[ 6 ] sequences extracted for gene ND3
[ 6 ] sequences extracted for gene ND4
[ 6 ] sequences extracted for gene ND4L
[ 6 ] sequences extracted for gene ND5
[ 6 ] sequences extracted for gene ND6
[ 0 ] sequences extracted for gene rrnL
[ 0 ] sequences extracted for gene rrnS

Extracted sequences can be found in ./mitophast/results/3.sequences

### PHYLOGENETIC ANALYSIS ###
Mode: pcg
Characters: aa
Command: /usr/local/MitoPhAST/V3.0/bin/build_trees.pl -in ./mitophast/results/3.sequences -out ./mitophast/work/phylogenetics -mito_gcode 5 -mode pcg -chars aa -bb on -bbrep 1000 -alrt on -alrtrep 1000 -cpu 12 -interactive on

Save run configurations: OK
Check genes: OK
Check characters: OK
Check files: OK

Check taxa: OK
Aligning sequences...sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_COX3.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_ND5.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_COX1.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_ATP6.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_ND4L.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_CYTB.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_ND4.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_COX2.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_ATP8.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_ND1.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_ND6.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_ND3.aa.align.fas: No such file or directory
sed: can't read /home/t/tchak/mitophast/work/phylogenetics/1.align/pcgaa/all_ND2.aa.align.fas: No such file or directory
done.
Concatenating sequences...
An error has occurred during concatenation, run terminated
cp: cannot stat './mitophast/work/phylogenetics/2.buildtree/*.tre': No such file or directory
cp: cannot stat './mitophast/work/phylogenetics/2.buildtree/*.fasta': No such file or directory
cp: cannot stat './mitophast/work/phylogenetics/2.buildtree/*.phy': No such file or directory

Alignment and tree files can be found in ./mitophast/results/4.trees

Error: Pipeline terminated - tree building step failed

**Comment by mh-tan** [comment]
Fixed.
